---
- hosts: all

  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "8080"

  roles:
    - geerlingguy.firewall
    - geerlingguy.ansible
    - geerlingguy.java
    - role: geerlingguy.jenkins
      jenkins_admin_username: admin
      jenkins_admin_password: admin
      jenkins_plugins:
        - git
        - ssh
        - github
        - ansicolor
  
  tasks: 
     - name: install maven
       apt: pkg="maven" state="present"
