---
- hosts: classops 
  become: yes
  tasks:
    
    - name: Install apt-packages
      apt: pkg={{ item }} state=present
      with_items:
        - git
        - python-dev
        - python-pip
        - python-setuptools
        - libyaml-dev
        - unzip
        - vim
        - gcc
        - cmake
        - build-essential

    - name: Upgrade pip
      pip:
        name: pip
        extra_args: --upgrade

    - name: Install deps
      pip: name={{item}}
      with_items:
        - PyYAML 
        - python-jenkins
        - pbr

    - name: ensure proper directories exists
      file:
        path: "{{item}}"
        state: directory
        mode: 0755
      with_items:
        - /tools
        - /etc/jenkins_jobs
        - /jobs

    - name: clone jenkins-job-builder repo.
      git:
        repo: 'https://git.openstack.org/openstack-infra/jenkins-job-builder'
        dest: /tools/jenkins-job-builder  

    - name: Install requirements
      pip:
        requirements: /tools/jenkins-job-builder/requirements.txt

    - name: Install test-requirements
      pip:
        requirements: /tools/jenkins-job-builder/test-requirements.txt


    - name: build jenkins-job-builder
      command: python setup.py install
      args:
        chdir: /tools/jenkins-job-builder


    - name: copy template
      template: 
        src: templates/jenkins.cfg
        dest: /etc/jenkins_jobs/jenkins_jobs.ini

    - name: copy template
      template: 
        src: templates/job.yml
        dest: /jobs/job.yml

